<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE qalab [<!ELEMENT qalab (summary,modules,file*)>
<!ATTLIST qalab version CDATA #REQUIRED>
<!ELEMENT summary (summaryresult*)>
<!ELEMENT modules (module*)>
<!ELEMENT file (result+)>
<!ATTLIST file id ID #REQUIRED>
<!ATTLIST file project CDATA #REQUIRED>
<!ATTLIST file module CDATA #REQUIRED>
<!ATTLIST file path CDATA #REQUIRED>
<!ELEMENT result EMPTY>
<!ATTLIST result date CDATA #REQUIRED>
<!ATTLIST result statvalue CDATA #REQUIRED>
<!ATTLIST result type CDATA #REQUIRED>
<!ELEMENT summaryresult EMPTY>
<!ATTLIST summaryresult project CDATA #REQUIRED>
<!ATTLIST summaryresult module CDATA #REQUIRED>
<!ATTLIST summaryresult date CDATA #REQUIRED>
<!ATTLIST summaryresult statvalue CDATA #REQUIRED>
<!ATTLIST summaryresult filecount CDATA #REQUIRED>
<!ATTLIST summaryresult type CDATA #REQUIRED>
<!ELEMENT module EMPTY>
<!ATTLIST module name CDATA #REQUIRED>
]>
<qalab version="1.2">
    <summary>
        <summaryresult date="2010-08-11" filecount="87" module="default"
            project="default" statvalue="565" type="checkstyle"/>
        <summaryresult date="2010-08-11" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-11" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-12" filecount="87" module="default"
            project="default" statvalue="565" type="checkstyle"/>
        <summaryresult date="2010-08-12" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-12" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-13" filecount="87" module="default"
            project="default" statvalue="565" type="checkstyle"/>
        <summaryresult date="2010-08-13" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-13" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-14" filecount="87" module="default"
            project="default" statvalue="555" type="checkstyle"/>
        <summaryresult date="2010-08-14" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-14" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-15" filecount="87" module="default"
            project="default" statvalue="555" type="checkstyle"/>
        <summaryresult date="2010-08-15" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-15" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-16" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-08-16" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-16" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-16" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-08-16" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-08-17" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-08-17" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-17" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-17" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-08-17" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-08-18" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-08-18" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-18" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-18" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-08-18" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-08-19" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-08-19" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-19" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-19" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-08-19" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-08-20" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-08-20" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-20" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-20" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-08-20" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-08-21" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-08-21" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-21" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-21" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-08-21" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-08-22" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-08-22" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-22" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-22" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-08-22" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-08-23" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-08-23" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-23" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-23" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-08-23" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-08-24" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-08-24" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-24" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-24" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-08-24" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-08-25" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-08-25" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-25" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-25" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-08-25" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-08-26" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-08-26" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-26" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-26" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-08-26" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-08-27" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-08-27" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-27" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-27" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-08-27" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-08-28" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-08-28" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-28" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-28" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-08-28" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-08-29" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-08-29" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-29" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-29" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-08-29" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-08-30" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-08-30" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-30" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-30" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-08-30" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-08-31" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-08-31" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-08-31" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-08-31" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-08-31" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-09-01" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-09-01" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-09-01" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-09-01" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-09-01" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-09-02" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-09-02" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-09-02" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-09-02" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-09-02" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-09-03" filecount="7" module="default"
            project="default" statvalue="58" type="checkstyle"/>
        <summaryresult date="2010-09-03" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-09-03" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-09-03" filecount="87" module="default"
            project="default" statvalue="1" type="cobertura-line"/>
        <summaryresult date="2010-09-03" filecount="87" module="default"
            project="default" statvalue="0" type="cobertura-branch"/>
        <summaryresult date="2010-09-04" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-09-04" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-09-04" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-09-05" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-09-05" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-09-05" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-09-06" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-09-06" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-09-06" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-09-07" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-09-07" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-09-07" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-09-26" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-09-26" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-09-26" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-09-27" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-09-27" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-09-27" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-09-28" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-09-28" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-09-28" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-01" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-01" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-01" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-02" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-02" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-02" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-03" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-03" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-03" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-04" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-04" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-04" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-05" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-05" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-05" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-06" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-06" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-06" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-07" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-07" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-07" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-08" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-08" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-08" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-09" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-09" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-09" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-10" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-10" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-10" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-11" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-11" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-11" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-13" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-13" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-13" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-14" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-14" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-14" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-15" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-15" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-15" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-17" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-17" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-17" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-18" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-18" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-18" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-19" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-19" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-19" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-20" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-20" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-20" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-21" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-21" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-21" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-22" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-22" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-22" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-23" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-23" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-23" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-24" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-24" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-24" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-25" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-25" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-25" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-26" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-26" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-26" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-27" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-27" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-27" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-28" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-28" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>
        <summaryresult date="2010-10-28" filecount="818"
            module="default" project="default" statvalue="0" type="javancss"/>
        <summaryresult date="2010-10-29" filecount="87" module="default"
            project="default" statvalue="554" type="checkstyle"/>
        <summaryresult date="2010-10-29" filecount="6" module="default"
            project="default" statvalue="169" type="pmd-cpd"/>